# Generated by Django 5.2 on 2026-02-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockBasic",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="股票代码",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "industry",
                    models.CharField(blank=True, max_length=50, verbose_name="行业"),
                ),
                (
                    "sector",
                    models.CharField(blank=True, max_length=50, verbose_name="板块"),
                ),
                ("market", models.CharField(max_length=10, verbose_name="市场")),
                (
                    "list_date",
                    models.DateField(blank=True, null=True, verbose_name="上市日期"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票基本信息",
                "verbose_name_plural": "股票基本信息",
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="来源"),
                ),
                ("url", models.URLField(blank=True, verbose_name="链接")),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="情感分数",
                    ),
                ),
                ("published_at", models.DateTimeField(verbose_name="发布时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_articles",
                        to="quant.stockbasic",
                        verbose_name="相关股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "财经新闻",
                "verbose_name_plural": "财经新闻",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="MoneyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="交易日期")),
                (
                    "main_net",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="主力净流入"
                    ),
                ),
                (
                    "huge_net",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="超大单净流入"
                    ),
                ),
                (
                    "big_net",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="大单净流入"
                    ),
                ),
                (
                    "mid_net",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="中单净流入"
                    ),
                ),
                (
                    "small_net",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="小单净流入"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_flows",
                        to="quant.stockbasic",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "资金流向",
                "verbose_name_plural": "资金流向",
                "unique_together": {("stock", "date")},
            },
        ),
        migrations.CreateModel(
            name="MarginData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="交易日期")),
                (
                    "margin_balance",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="融资余额"
                    ),
                ),
                (
                    "short_balance",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="融券余额"
                    ),
                ),
                (
                    "margin_buy",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="融资买入额"
                    ),
                ),
                (
                    "margin_repay",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="融资偿还额"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="margin_data",
                        to="quant.stockbasic",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "融资融券数据",
                "verbose_name_plural": "融资融券数据",
                "unique_together": {("stock", "date")},
            },
        ),
        migrations.CreateModel(
            name="KlineData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="交易日期")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="开盘价"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最高价"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最低价"
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="收盘价"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量（手）")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=16, verbose_name="成交额（元）"
                    ),
                ),
                (
                    "turnover",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="涨跌幅(%)",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="klines",
                        to="quant.stockbasic",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "K线数据",
                "verbose_name_plural": "K线数据",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=10, verbose_name="报告期")),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="市盈率",
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="市净率",
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="净资产收益率(%)",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="营业收入",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=16,
                        null=True,
                        verbose_name="净利润",
                    ),
                ),
                (
                    "gross_margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="毛利率(%)",
                    ),
                ),
                (
                    "debt_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="资产负债率(%)",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(blank=True, null=True, verbose_name="报告发布日"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_reports",
                        to="quant.stockbasic",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "财务报告",
                "verbose_name_plural": "财务报告",
                "unique_together": {("stock", "period")},
            },
        ),
    ]
