# Generated by Django 6.0.2 on 2026-02-26 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quant", "0002_create_hypertables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="组合名称")),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000,
                        max_digits=16,
                        verbose_name="初始资金",
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000,
                        max_digits=16,
                        verbose_name="现金余额",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "模拟组合",
                "verbose_name_plural": "模拟组合",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "买入"), ("SELL", "卖出")],
                        max_length=4,
                        verbose_name="交易类型",
                    ),
                ),
                ("shares", models.IntegerField(verbose_name="交易数量")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="成交价格"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="成交金额"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="手续费"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="交易理由"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="quant.portfolio",
                        verbose_name="组合",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="quant.stockbasic",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易记录",
                "verbose_name_plural": "交易记录",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="总资产"
                    ),
                ),
                (
                    "daily_return",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="日收益率(%)",
                    ),
                ),
                (
                    "cumulative_return",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="累计收益率(%)",
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="最大回撤(%)",
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="夏普比率",
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="胜率(%)",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="quant.portfolio",
                        verbose_name="组合",
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效指标",
                "verbose_name_plural": "绩效指标",
                "ordering": ["-date"],
                "unique_together": {("portfolio", "date")},
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.IntegerField(default=0, verbose_name="持仓数量")),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="平均成本"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="当前价格"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="quant.portfolio",
                        verbose_name="组合",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="quant.stockbasic",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "持仓",
                "verbose_name_plural": "持仓",
                "unique_together": {("portfolio", "stock")},
            },
        ),
    ]
